# Generated by Django 5.1.7 on 2025-03-08 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0002_certificate_name_alter_it_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='about_school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school_rating', to='it_school.aboutschool'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_course', to='it_school.courses'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='master_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rating_master', to='it_school.masterclass'),
        ),
    ]
