# Generated by Django 5.1.7 on 2025-03-08 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0003_alter_rating_about_school_alter_rating_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutschool',
            old_name='name',
            new_name='about_school',
        ),
        migrations.RenameField(
            model_name='aboutschool',
            old_name='name_ky',
            new_name='about_school_ky',
        ),
        migrations.RenameField(
            model_name='aboutschool',
            old_name='name_ru',
            new_name='about_school_ru',
        ),
    ]
