# Generated by Django 5.1.7 on 2025-03-08 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0004_rename_name_aboutschool_about_school_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='image',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='name',
        ),
        migrations.CreateModel(
            name='RatingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='rating_image')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_user', to='it_school.rating')),
            ],
        ),
    ]
