# Generated by Django 5.1.7 on 2025-03-09 07:33

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0005_remove_rating_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paket',
            name='choices',
        ),
        migrations.RemoveField(
            model_name='paket',
            name='price',
        ),
        migrations.RemoveField(
            model_name='paket',
            name='status',
        ),
        migrations.RemoveField(
            model_name='paket',
            name='time',
        ),
        migrations.CreateModel(
            name='PaketSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('choices', models.CharField(choices=[('Ежемесячно', 'Ежемесячно'), ('Ежегодно', 'Ежегодно')], default='Ежегодно', max_length=100)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('Все статьи', 'Все статьи'), ('Все мастер классы', 'Все мастер классы'), ('6 новых статей каждый месяц', '6 новых статей каждый месяц'), ('Доступ к курсу “DevOps - инженер”', 'Доступ к курсу “DevOps - инженер”')], max_length=90)),
                ('paket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paket', to='it_school.paket')),
            ],
        ),
    ]
