# Generated by Django 5.1.7 on 2025-03-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0006_remove_paket_choices_remove_paket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='description',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='question',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_ky',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_ru',
        ),
        migrations.CreateModel(
            name='QuestionSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('question_ru', models.CharField(max_length=100, null=True)),
                ('question_ky', models.CharField(max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='all_question', to='it_school.question')),
            ],
        ),
    ]
