# Generated by Django 5.1.7 on 2025-03-09 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0007_remove_question_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutcourses',
            name='course_ky',
        ),
        migrations.RemoveField(
            model_name='aboutcourses',
            name='course_ru',
        ),
        migrations.RemoveField(
            model_name='questionsecond',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='questionsecond',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='questionsecond',
            name='question_ky',
        ),
        migrations.RemoveField(
            model_name='questionsecond',
            name='question_ru',
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='about',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='about_ky',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='about_ru',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='master_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_master_class', to='it_school.masterclass'),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='title',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='title_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='aboutcourses',
            name='title_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='included',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='courses',
            name='name',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='access',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='included',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='name',
            field=models.CharField(default=0, max_length=24),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='name_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='name_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcourses',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='about_courses', to='it_school.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access_ky',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access_ru',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='title',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='title_ky',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='title_ru',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='questionsecond',
            name='questions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_question', to='it_school.question'),
        ),
        migrations.CreateModel(
            name='AboutSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=64)),
                ('title_ru', models.CharField(default=0, max_length=64, null=True)),
                ('title_ky', models.CharField(default=0, max_length=64, null=True)),
                ('description', models.TextField(default=0)),
                ('description_ru', models.TextField(default=0, null=True)),
                ('description_ky', models.TextField(default=0, null=True)),
                ('about_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_second', to='it_school.aboutcourses')),
            ],
        ),
    ]
