# Generated by Django 5.1.7 on 2025-03-09 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0008_remove_aboutcourses_course_ky_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='description',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='title',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='title_ru',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='access_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='access_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='included_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='included_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.CreateModel(
            name='MasterClassSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=100)),
                ('title_ru', models.CharField(default=0, max_length=100, null=True)),
                ('title_ky', models.CharField(default=0, max_length=100, null=True)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_ky', models.TextField(null=True)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master', to='it_school.masterclass')),
            ],
        ),
    ]
