# Generated by Django 5.1.2 on 2025-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0009_remove_masterclass_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcourses',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcourses',
            name='description_ky',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aboutcourses',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
