# Generated by Django 5.1.2 on 2025-03-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0011_alter_masterclasssecond_master'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='included_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='included_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ky',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='courses',
            name='name_ru',
            field=models.CharField(default=0, max_length=24, null=True),
        ),
    ]
