# Generated by Django 5.1.2 on 2025-03-09 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0012_courses_included_ky_courses_included_ru_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutschool',
            name='school_description',
        ),
        migrations.RemoveField(
            model_name='aboutschool',
            name='school_description_ky',
        ),
        migrations.RemoveField(
            model_name='aboutschool',
            name='school_description_ru',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='description',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='master_name',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access_ky',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='access_ru',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AboutSchoolSecond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=0, max_length=50)),
                ('school_description', models.TextField(default=0)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='it_school.aboutschool')),
            ],
        ),
        migrations.DeleteModel(
            name='MasterClassSecond',
        ),
    ]
