# Generated by Django 5.1.2 on 2025-03-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('it_school', '0013_remove_aboutschool_school_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterclass',
            name='description_ky',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='description_ru',
            field=models.TextField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='master_name_ky',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='master_name_ru',
            field=models.CharField(default=0, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='access',
            field=models.CharField(blank=True, default=0, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='access_ky',
            field=models.CharField(blank=True, default=0, max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='access_ru',
            field=models.CharField(blank=True, default=0, max_length=24, null=True),
        ),
    ]
